import { describe, expect, it } from 'vitest';
import type { PlanResult } from '@forgemind/providers';
import { buildRoadmapStepTaskPrompt, findFirstPendingStepForLatestCycle, resolveTaskMode, toImplementationStepBlueprints, toProjectContract } from './routes.js';

const projectContract = {
  version: 1,
  summary: 'Math practice application',
  invariants: ['Exercises are deterministic in tests.'],
  prohibitedSubstitutes: ['Static screenshots instead of working UI.'],
  requirements: [
    { id: 'REQ-SCOPE', title: 'Documented scope', description: 'Supported grades and operations are explicit.', acceptanceCriteria: ['Scope is documented.'] },
    { id: 'REQ-GENERATOR', title: 'Exercise generator', description: 'Exercises are generated by grade.', acceptanceCriteria: ['Generator tests pass.'] }
  ],
  releaseCriteria: ['Production build succeeds.']
};

describe('project roadmap generation', () => {
  it('preserves independent scope and acceptance criteria for every step', () => {
    const plan: PlanResult = {
      summary: 'Roadmap',
      steps: ['Document scope', 'Build generator'],
      acceptanceCriteria: ['Project-wide criterion that must not be copied'],
      implementationSteps: [
        {
          title: 'Document MVP scope',
          description: 'Write the product and technical scope before implementation.',
          acceptanceCriteria: ['The MVP scope document defines supported grades and operations.'],
          inScope: ['Documentation'],
          outOfScope: ['Application source code'],
          requirementIds: ['REQ-SCOPE'],
          deliverables: ['MVP scope document']
        },
        {
          title: 'Build exercise generator',
          description: 'Implement deterministic grade-specific arithmetic generation.',
          acceptanceCriteria: ['Generator tests cover every supported grade and operation.'],
          inScope: ['Generator module', 'Generator tests'],
          outOfScope: ['Practice UI'],
          requirementIds: ['REQ-GENERATOR'],
          deliverables: ['Generator module', 'Automated generator tests']
        }
      ],
      projectContract
    };

    const normalizedContract = toProjectContract(plan, 'Math practice application brief');
    expect(normalizedContract).toMatchObject(projectContract);
    expect(normalizedContract.sourceBriefHash).toMatch(/^[a-f0-9]{64}$/);
    expect(toImplementationStepBlueprints(plan, projectContract)).toEqual([
      {
        title: 'Document MVP scope',
        description: 'Write the product and technical scope before implementation.\n\nIn scope:\n- Documentation\n\nOut of scope:\n- Application source code',
        acceptanceCriteria: ['The MVP scope document defines supported grades and operations.'],
        requirementIds: ['REQ-SCOPE'],
        deliverables: ['MVP scope document']
      },
      {
        title: 'Build exercise generator',
        description: 'Implement deterministic grade-specific arithmetic generation.\n\nIn scope:\n- Generator module\n- Generator tests\n\nOut of scope:\n- Practice UI',
        acceptanceCriteria: ['Generator tests cover every supported grade and operation.'],
        requirementIds: ['REQ-GENERATOR'],
        deliverables: ['Generator module', 'Automated generator tests']
      }
    ]);
  });

  it('rejects an unstructured provider response instead of duplicating global criteria', () => {
    expect(() => toImplementationStepBlueprints({
      summary: 'Legacy roadmap',
      steps: ['One', 'Two'],
      acceptanceCriteria: ['Everything works']
    }, projectContract)).toThrow('structured implementationSteps');
  });

  it('rejects a roadmap that leaves a contract requirement uncovered', () => {
    const plan: PlanResult = {
      summary: 'Incomplete roadmap',
      steps: [],
      acceptanceCriteria: [],
      projectContract,
      implementationSteps: [{
        title: 'Document scope',
        description: 'Document scope.',
        acceptanceCriteria: ['Scope exists.'],
        inScope: ['Documentation'],
        outOfScope: [],
        requirementIds: ['REQ-SCOPE'],
        deliverables: ['Scope document']
      }]
    };

    expect(() => toImplementationStepBlueprints(plan, projectContract)).toThrow('REQ-GENERATOR');
  });

  it('rejects broad work items instead of accepting an epic as one task', () => {
    const plan: PlanResult = {
      summary: 'Oversized roadmap',
      steps: [],
      acceptanceCriteria: [],
      projectContract,
      implementationSteps: [{
        title: 'Build everything',
        description: 'Build all layers.',
        acceptanceCriteria: ['One', 'Two'],
        inScope: ['One', 'Two', 'Three', 'Four', 'Five', 'Six'],
        outOfScope: [],
        requirementIds: ['REQ-SCOPE', 'REQ-GENERATOR'],
        deliverables: ['App', 'Tests']
      }]
    };

    expect(() => toImplementationStepBlueprints(plan, projectContract)).toThrow('oversized implementation step');
  });

  it('makes completed and future step boundaries explicit without duplicating the title', () => {
    const prompt = buildRoadmapStepTaskPrompt({
      projectName: 'Mathematica',
      objective: 'Build a math practice app.',
      stepTitle: 'Build exercise generator',
      stepDescription: 'Implement grade-specific generation.\n\nIn scope:\n- Generator\n\nOut of scope:\n- UI',
      acceptanceCriteria: ['Generator tests pass.'],
      completedSteps: ['Document MVP scope'],
      futureSteps: ['Build practice UI']
    });

    expect(prompt.match(/Build exercise generator/g)).toHaveLength(1);
    expect(prompt).toContain('Already completed roadmap steps (existing repository context):\n- Document MVP scope');
    expect(prompt).toContain('Future roadmap steps (explicitly out of scope):\n- Build practice UI');
    expect(prompt).toContain('Do not implement work assigned to future roadmap steps.');
  });

  it('starts only the first pending step from the latest roadmap cycle', () => {
    expect(findFirstPendingStepForLatestCycle({
      cycles: [
        { id: 'old', cycleNumber: 1 },
        { id: 'latest', cycleNumber: 2 }
      ],
      steps: [
        { cycleId: 'old', sequenceNumber: 2, status: 'pending' },
        { cycleId: 'latest', sequenceNumber: 2, status: 'pending' },
        { cycleId: 'latest', sequenceNumber: 1, status: 'pending' }
      ]
    })).toEqual({ cycleId: 'latest', sequenceNumber: 1, status: 'pending' });
  });

  it('uses the project task mode unless a task explicitly overrides it', () => {
    expect(resolveTaskMode(undefined, 'full_auto')).toBe('full_auto');
    expect(resolveTaskMode('safe', 'full_auto')).toBe('safe');
    expect(resolveTaskMode(undefined, undefined)).toBe('safe');
  });
});
