import { describe, expect, it, vi } from 'vitest';
import type { AIProvider, ImplementationStepPlan, PlanResult } from '@forgemind/providers';
import { buildImplementationStepBlueprintsWithRepairs, buildRoadmapPlanningPrompt, buildRoadmapStepTaskPrompt, collectRegeneratedRoadmapRequirementIds, createProjectPlanningSession, findFirstPendingStepForLatestCycle, repairRoadmapOnce, resolveRegeneratedProjectContract, resolveTaskMode, selectUnfinishedRoadmapSteps, toImplementationStepBlueprints, toProjectArchitectureUpdate, toProjectContract } from './routes.js';

const projectContract = {
  version: 1,
  summary: 'Math practice application',
  invariants: ['Exercises are deterministic in tests.'],
  prohibitedSubstitutes: ['Static screenshots instead of working UI.'],
  requirements: [
    { id: 'REQ-SCOPE', title: 'Documented scope', description: 'Supported grades and operations are explicit.', acceptanceCriteria: ['Scope is documented.'], briefReferences: ['supported grades and operations'] },
    { id: 'REQ-GENERATOR', title: 'Exercise generator', description: 'Exercises are generated by grade.', acceptanceCriteria: ['Generator tests pass.'], briefReferences: ['generated arithmetic exercises'] }
  ],
  releaseCriteria: ['Production build succeeds.']
};

describe('project roadmap generation', () => {
  it('requires a structured initial architecture from roadmap planning', () => {
    expect(toProjectArchitectureUpdate({
      summary: 'Roadmap', steps: [], acceptanceCriteria: [],
      architectureUpdate: {
        summary: 'Layered application.',
        modules: [{ name: 'UI', responsibility: 'User interaction.', paths: ['src/ui/**'], publicInterfaces: ['App'], dependencies: ['Domain'] }],
        decisions: [], conventions: ['Keep UI state local.'], dependencyRules: ['UI depends on Domain.'],
        knownDebt: [], resolvedDebt: []
      }
    })).toMatchObject({ summary: 'Layered application.', modules: [{ name: 'UI' }] });

    expect(() => toProjectArchitectureUpdate({
      summary: 'Roadmap', steps: [], acceptanceCriteria: [],
      architectureUpdate: {
        summary: 'No modules.', modules: [], decisions: [], conventions: [], dependencyRules: [],
        knownDebt: [], resolvedDebt: []
      }
    }, true)).toThrow('initial project architecture module');
  });

  it('accepts an empty architecture delta for an extension', () => {
    expect(toProjectArchitectureUpdate({
      summary: 'Extension', steps: [], acceptanceCriteria: [],
      architectureUpdate: {
        summary: undefined, modules: [], decisions: [], conventions: [], dependencyRules: [],
        knownDebt: [], resolvedDebt: []
      }
    })).toMatchObject({ modules: [], decisions: [] });
  });

  it('resumes only a compatible project planning session and persists provider updates', async () => {
    const updateProjectPlanningSession = vi.fn(async () => undefined);
    const session = createProjectPlanningSession(
      { updateProjectPlanningSession } as never,
      {
        id: 'project_1', name: 'Demo', slug: 'demo', defaultBranch: 'main', isActive: true,
        planningSessionId: 'thread_1', planningSessionProvider: 'codex', planningSessionModel: 'gpt-5.5',
        planningSessionConnectionId: 'connection_1', createdAt: '', updatedAt: ''
      },
      {
        id: 'connection_1', userId: 'user_1', name: 'Codex', isDefault: true, credentialSource: 'codex_oauth',
        provider: 'codex', authMode: 'codex_oauth', model: 'gpt-5.5', connectedAt: '', updatedAt: ''
      }
    );

    expect(session.id).toBe('thread_1');
    await session.onUpdate?.({ id: 'thread_2', provider: 'codex', model: 'gpt-5.5' });
    expect(updateProjectPlanningSession).toHaveBeenCalledWith({
      projectId: 'project_1', sessionId: 'thread_2', provider: 'codex', model: 'gpt-5.5', connectionId: 'connection_1'
    });

    const incompatible = createProjectPlanningSession(
      { updateProjectPlanningSession } as never,
      {
        id: 'project_1', name: 'Demo', slug: 'demo', defaultBranch: 'main', isActive: true,
        planningSessionId: 'thread_1', planningSessionProvider: 'codex', planningSessionModel: 'old-model',
        planningSessionConnectionId: 'connection_1', createdAt: '', updatedAt: ''
      },
      {
        id: 'connection_1', userId: 'user_1', name: 'Codex', isDefault: true, credentialSource: 'codex_oauth',
        provider: 'codex', authMode: 'codex_oauth', model: 'gpt-5.5', connectedAt: '', updatedAt: ''
      }
    );
    expect(incompatible.id).toBeUndefined();

    const forcedFresh = createProjectPlanningSession(
      { updateProjectPlanningSession } as never,
      {
        id: 'project_1', name: 'Demo', slug: 'demo', defaultBranch: 'main', isActive: true,
        planningSessionId: 'thread_1', planningSessionProvider: 'codex', planningSessionModel: 'gpt-5.5',
        planningSessionConnectionId: 'connection_1', createdAt: '', updatedAt: ''
      },
      {
        id: 'connection_1', userId: 'user_1', name: 'Codex', isDefault: true, credentialSource: 'codex_oauth',
        provider: 'codex', authMode: 'codex_oauth', model: 'gpt-5.5', connectedAt: '', updatedAt: ''
      },
      true
    );
    expect(forcedFresh.id).toBeUndefined();
  });

  it('uses a compact continuation prompt without resending the project brief', () => {
    const prompt = buildRoadmapPlanningPrompt({
      project: { name: 'Demo', brief: 'A deliberately long project brief that the session already contains.' },
      objective: 'Add reporting',
      completedSteps: ['Build core'],
      continuation: true
    });

    expect(prompt).toContain('Add reporting');
    expect(prompt).toContain('Build core');
    expect(prompt).not.toContain('deliberately long project brief');
  });

  it('requests a delta against the persisted contract for an extension', () => {
    const prompt = buildRoadmapPlanningPrompt({
      project: { name: 'Demo', brief: 'The complete brief is intentionally not repeated.' },
      objective: 'Add reporting',
      completedSteps: ['Build core'],
      continuation: true,
      currentContract: projectContract
    });

    expect(prompt).toContain('contractDelta with baseVersion 1');
    expect(prompt).toContain('REQ-SCOPE');
    expect(prompt).toContain('projectContract as null');
    expect(prompt).toContain('Requirements omitted from the delta remain active and unchanged');
    expect(prompt).not.toContain('complete brief is intentionally not repeated');
  });

  it('requires unfinished roadmap work to survive contract regeneration', () => {
    const prompt = buildRoadmapPlanningPrompt({
      project: { name: 'Demo', brief: 'Complete brief.' },
      objective: 'Revise regional scope',
      completedSteps: ['Build core'],
      unfinishedSteps: [
        { title: 'Ship installer', requirementIds: ['REQ-INSTALLER', 'REQ-RELEASE'] },
        { title: 'Run stability QA', requirementIds: ['REQ-STABILITY'] }
      ],
      continuation: true,
      currentContract: projectContract
    });

    expect(prompt).toContain('Carry forward every unfinished work item');
    expect(prompt).toContain('Ship installer [REQ-INSTALLER, REQ-RELEASE]');
    expect(prompt).toContain('Run stability QA [REQ-STABILITY]');
    expect(prompt).toContain('finish all carried-forward work');
  });

  it('validates regenerated roadmaps against changed and unfinished active requirements', () => {
    const contract = {
      ...projectContract,
      requirements: [
        ...projectContract.requirements.map((requirement) => ({ ...requirement, status: 'active' as const })),
        {
          id: 'REQ-REMOVED', title: 'Removed capability', description: 'No longer required.',
          acceptanceCriteria: ['Not applicable.'], briefReferences: ['removed'], status: 'removed' as const
        }
      ]
    };

    expect(collectRegeneratedRoadmapRequirementIds(
      contract,
      ['REQ-SCOPE'],
      [{ requirementIds: ['REQ-GENERATOR', 'REQ-REMOVED'] }]
    )).toEqual(['REQ-SCOPE', 'REQ-GENERATOR']);
  });

  it('carries unfinished steps only from the selected recovery contract', () => {
    const unfinished = selectUnfinishedRoadmapSteps({
      cycles: [
        { id: 'cycle_v1', contractVersionId: 'contract_v1' },
        { id: 'cycle_v2', contractVersionId: 'contract_v2' }
      ],
      steps: [
        { cycleId: 'cycle_v1', title: 'Completed foundation', status: 'completed', requirementIds: ['REQ-SCOPE'] },
        { cycleId: 'cycle_v1', title: 'Ship installer', status: 'pending', requirementIds: ['REQ-GENERATOR'] },
        { cycleId: 'cycle_v2', title: 'Bad replacement work', status: 'pending', requirementIds: ['REQ-REMOVED'] }
      ]
    }, 'contract_v1');

    expect(unfinished).toEqual([{ title: 'Ship installer', requirementIds: ['REQ-GENERATOR'] }]);
  });

  it('applies brief revisions as a delta without dropping unchanged completed requirements', () => {
    const plan: PlanResult = {
      summary: 'Revise supported scope.',
      steps: [],
      acceptanceCriteria: [],
      projectContract: undefined,
      contractDelta: {
        baseVersion: 1,
        summary: 'Math practice application with revised documented scope.',
        addRequirements: [],
        updateRequirements: [{
          id: 'REQ-SCOPE',
          description: 'Supported grades, operations, and regional rules are explicit.',
          briefReferences: ['revised supported grades and regional rules'],
          rationale: 'The user revised the supported product scope.'
        }],
        supersedeRequirements: [],
        removeRequirements: [],
        invariantChanges: { add: [], remove: [] },
        prohibitedSubstituteChanges: { add: [], remove: [] },
        releaseCriteriaChanges: { add: [], remove: [] },
        migrationImpacts: [],
        compatibilityImpacts: []
      },
      implementationSteps: []
    };

    const result = resolveRegeneratedProjectContract(
      plan,
      'Revised complete project specification.',
      'Revised complete project specification.',
      projectContract
    );

    expect(result.projectContract.version).toBe(2);
    expect(result.projectContract.requirements.map((requirement) => requirement.id)).toEqual([
      'REQ-SCOPE',
      'REQ-GENERATOR'
    ]);
    expect(result.projectContract.requirements.find((requirement) => requirement.id === 'REQ-GENERATOR'))
      .toMatchObject(projectContract.requirements[1]!);
    expect(result.touchedRequirementIds).toEqual(['REQ-SCOPE']);
    expect(result.contractDelta?.baseVersion).toBe(1);

    const recovered = resolveRegeneratedProjectContract(
      plan,
      'Revised complete project specification.',
      'Revised complete project specification.',
      projectContract,
      3
    );
    expect(recovered.projectContract.version).toBe(3);
    expect(recovered.projectContract.requirements).toEqual(result.projectContract.requirements);
  });

  it('preserves independent scope and acceptance criteria for every step', () => {
    const plan: PlanResult = {
      summary: 'Roadmap',
      steps: ['Document scope', 'Build generator'],
      acceptanceCriteria: ['Project-wide criterion that must not be copied'],
      implementationSteps: [
        {
          title: 'Document MVP scope',
          description: 'Write the product and technical scope before implementation.',
          acceptanceCriteria: ['The MVP scope document defines supported grades and operations.'],
          inScope: ['Documentation'],
          outOfScope: ['Application source code'],
          requirementIds: ['REQ-SCOPE'],
          deliverables: ['MVP scope document'],
          changeRationale: 'Establish the requirement boundary before implementation.',
          dependsOnStepTitles: [],
          validationFocus: ['implementation']
        },
        {
          title: 'Build exercise generator',
          description: 'Implement deterministic grade-specific arithmetic generation.',
          acceptanceCriteria: ['Generator tests cover every supported grade and operation.'],
          inScope: ['Generator module', 'Generator tests'],
          outOfScope: ['Practice UI'],
          requirementIds: ['REQ-GENERATOR'],
          deliverables: ['Generator module', 'Automated generator tests'],
          changeRationale: 'Implement the generator requirement.',
          dependsOnStepTitles: ['Document MVP scope'],
          validationFocus: ['implementation']
        }
      ],
      projectContract
    };

    const normalizedContract = toProjectContract(plan, 'Math practice application brief');
    expect(normalizedContract).toMatchObject(projectContract);
    expect(normalizedContract.sourceBriefHash).toMatch(/^[a-f0-9]{64}$/);
    expect(normalizedContract.sourceBriefSnapshot).toBe('Math practice application brief');
    expect(toImplementationStepBlueprints(plan, projectContract)).toEqual([
      {
        title: 'Document MVP scope',
        description: 'Write the product and technical scope before implementation.\n\nIn scope:\n- Documentation\n\nOut of scope:\n- Application source code',
        acceptanceCriteria: ['The MVP scope document defines supported grades and operations.'],
        requirementIds: ['REQ-SCOPE'],
        deliverables: ['MVP scope document'],
        changeRationale: 'Establish the requirement boundary before implementation.',
        dependsOnStepTitles: [],
        validationFocus: ['implementation']
      },
      {
        title: 'Build exercise generator',
        description: 'Implement deterministic grade-specific arithmetic generation.\n\nIn scope:\n- Generator module\n- Generator tests\n\nOut of scope:\n- Practice UI',
        acceptanceCriteria: ['Generator tests cover every supported grade and operation.'],
        requirementIds: ['REQ-GENERATOR'],
        deliverables: ['Generator module', 'Automated generator tests'],
        changeRationale: 'Implement the generator requirement.',
        dependsOnStepTitles: ['Document MVP scope'],
        validationFocus: ['implementation']
      }
    ]);
  });

  it('rejects an unstructured provider response instead of duplicating global criteria', () => {
    expect(() => toImplementationStepBlueprints({
      summary: 'Legacy roadmap',
      steps: ['One', 'Two'],
      acceptanceCriteria: ['Everything works']
    }, projectContract)).toThrow('structured implementationSteps');
  });

  it('rejects a roadmap that leaves a contract requirement uncovered', () => {
    const plan: PlanResult = {
      summary: 'Incomplete roadmap',
      steps: [],
      acceptanceCriteria: [],
      projectContract,
      implementationSteps: [{
        title: 'Document scope',
        description: 'Document scope.',
        acceptanceCriteria: ['Scope exists.'],
        inScope: ['Documentation'],
        outOfScope: [],
        requirementIds: ['REQ-SCOPE'],
        deliverables: ['Scope document'],
        changeRationale: 'Document the scope requirement.',
        dependsOnStepTitles: [],
        validationFocus: ['implementation']
      }]
    };

    expect(() => toImplementationStepBlueprints(plan, projectContract)).toThrow('REQ-GENERATOR');
  });

  it('adds the default implementation validation focus without an AI repair', () => {
    const plan: PlanResult = {
      summary: 'Roadmap with specialized validation metadata',
      steps: [],
      acceptanceCriteria: [],
      projectContract,
      implementationSteps: [{
        title: 'Document scope',
        description: 'Document the supported product scope.',
        acceptanceCriteria: ['The scope document is reviewed.'],
        inScope: ['Scope documentation'],
        outOfScope: [],
        requirementIds: ['REQ-SCOPE'],
        deliverables: ['Scope document'],
        changeRationale: 'Establish the scope boundary.',
        dependsOnStepTitles: [],
        validationFocus: ['regression']
      }, {
        title: 'Build exercise generator',
        description: 'Implement deterministic exercise generation.',
        acceptanceCriteria: ['Generator tests pass.'],
        inScope: ['Generator implementation'],
        outOfScope: [],
        requirementIds: ['REQ-GENERATOR'],
        deliverables: ['Generator module'],
        changeRationale: 'Implement the generator requirement.',
        dependsOnStepTitles: ['Document scope'],
        validationFocus: []
      }]
    };

    const blueprints = toImplementationStepBlueprints(plan, projectContract);

    expect(blueprints[0]!.validationFocus).toEqual(['implementation', 'regression']);
    expect(blueprints[1]!.validationFocus).toEqual(['implementation']);
  });

  it('rejects broad work items instead of accepting an epic as one task', () => {
    const plan: PlanResult = {
      summary: 'Oversized roadmap',
      steps: [],
      acceptanceCriteria: [],
      projectContract,
      implementationSteps: [{
        title: 'Build everything',
        description: 'Build all layers.',
        acceptanceCriteria: ['One', 'Two'],
        inScope: ['One', 'Two', 'Three', 'Four', 'Five', 'Six'],
        outOfScope: [],
        requirementIds: ['REQ-SCOPE', 'REQ-GENERATOR'],
        deliverables: ['App', 'Tests'],
        changeRationale: 'Implement the requested capabilities.',
        dependsOnStepTitles: [],
        validationFocus: ['implementation']
      }]
    };

    expect(() => toImplementationStepBlueprints(plan, projectContract)).toThrow('oversized implementation step');
  });

  it('rejects extension steps that cross the changed contract scope', () => {
    const plan: PlanResult = {
      summary: 'Scope crossing roadmap',
      steps: [],
      acceptanceCriteria: [],
      implementationSteps: [{
        title: 'Rewrite documented scope',
        description: 'Change an unrelated completed capability.',
        acceptanceCriteria: ['Scope is rewritten.'],
        inScope: ['Documentation'],
        outOfScope: [],
        requirementIds: ['REQ-SCOPE'],
        deliverables: ['Updated scope'],
        changeRationale: 'Unrelated cleanup.',
        dependsOnStepTitles: [],
        validationFocus: ['implementation', 'regression']
      }]
    };

    expect(() => toImplementationStepBlueprints(plan, projectContract, ['REQ-GENERATOR'], {
      extension: true
    })).toThrow('crosses the contract delta scope');
  });

  it('allows exactly one targeted provider repair without resending the contract', async () => {
    const invalidSteps: ImplementationStepPlan[] = [{
      title: 'Build generator',
      description: 'Implement generator.',
      acceptanceCriteria: ['Tests pass.'],
      inScope: ['Generator'],
      outOfScope: [],
      requirementIds: ['REQ-GENERATOR'],
      deliverables: ['Generator'],
      changeRationale: '',
      dependsOnStepTitles: [],
      validationFocus: ['implementation']
    }];
    const repairRoadmap = vi.fn().mockResolvedValue({
      implementationSteps: [{
        ...invalidSteps[0],
        changeRationale: 'Implement the changed generator requirement.',
        validationFocus: ['implementation', 'regression']
      }]
    });
    const provider = { kind: 'codex', repairRoadmap } as unknown as AIProvider;
    const plan = await repairRoadmapOnce(provider, {}, {
      summary: 'Roadmap',
      steps: [],
      acceptanceCriteria: [],
      implementationSteps: invalidSteps
    }, {
      taskId: 'project_1',
      objective: 'Extend generator',
      validationError: 'Missing rationale',
      allowedRequirementIds: ['REQ-GENERATOR'],
      completedStepTitles: ['Document scope'],
      migrationImpacts: [],
      compatibilityImpacts: []
    });

    expect(repairRoadmap).toHaveBeenCalledTimes(1);
    expect(repairRoadmap.mock.calls[0]![0]).not.toHaveProperty('projectContract');
    expect(plan.implementationSteps?.[0]?.changeRationale).toContain('changed generator');
  });

  it('revalidates targeted roadmap repairs and allows one bounded follow-up repair', async () => {
    const repairRoadmap = vi.fn()
      .mockResolvedValueOnce({ implementationSteps: [{ title: 'still invalid' }] })
      .mockResolvedValueOnce({ implementationSteps: [{ title: 'valid' }] });
    const provider = { kind: 'codex', repairRoadmap } as unknown as AIProvider;
    const validate = vi.fn((plan: PlanResult) => {
      if (plan.implementationSteps?.[0]?.title !== 'valid') throw new Error('Roadmap is still invalid.');
      return ['validated'];
    });

    const result = await buildImplementationStepBlueprintsWithRepairs({
      provider,
      session: {},
      plan: { summary: 'Roadmap', steps: [], acceptanceCriteria: [], implementationSteps: [{ title: 'invalid' } as ImplementationStepPlan] },
      repairInput: {
        taskId: 'project_1',
        objective: 'Build qualification project',
        allowedRequirementIds: ['REQ-FOUNDATION'],
        completedStepTitles: [],
        migrationImpacts: [],
        compatibilityImpacts: []
      },
      validate
    });

    expect(repairRoadmap).toHaveBeenCalledTimes(2);
    expect(validate).toHaveBeenCalledTimes(3);
    expect(result.blueprints).toEqual(['validated']);
  });

  it('makes completed and future step boundaries explicit without duplicating the title', () => {
    const prompt = buildRoadmapStepTaskPrompt({
      projectName: 'Mathematica',
      objective: 'Build a math practice app.',
      stepTitle: 'Build exercise generator',
      stepDescription: 'Implement grade-specific generation.\n\nIn scope:\n- Generator\n\nOut of scope:\n- UI',
      acceptanceCriteria: ['Generator tests pass.'],
      completedSteps: ['Document MVP scope'],
      futureSteps: ['Build practice UI']
    });

    expect(prompt.match(/Build exercise generator/g)).toHaveLength(1);
    expect(prompt).toContain('Already completed roadmap steps (existing repository context):\n- Document MVP scope');
    expect(prompt).toContain('Future roadmap steps (explicitly out of scope):\n- Build practice UI');
    expect(prompt).toContain('Do not implement work assigned to future roadmap steps.');
  });

  it('starts only the first pending step from the latest roadmap cycle', () => {
    expect(findFirstPendingStepForLatestCycle({
      cycles: [
        { id: 'old', cycleNumber: 1 },
        { id: 'latest', cycleNumber: 2 }
      ],
      steps: [
        { cycleId: 'old', sequenceNumber: 2, status: 'pending' },
        { cycleId: 'latest', sequenceNumber: 2, status: 'pending' },
        { cycleId: 'latest', sequenceNumber: 1, status: 'pending' }
      ]
    })).toEqual({ cycleId: 'latest', sequenceNumber: 1, status: 'pending' });
  });

  it('uses the project task mode unless a task explicitly overrides it', () => {
    expect(resolveTaskMode(undefined, 'full_auto')).toBe('full_auto');
    expect(resolveTaskMode('safe', 'full_auto')).toBe('safe');
    expect(resolveTaskMode(undefined, undefined)).toBe('safe');
  });
});
